services:
  xbvr:
    container_name: xbvr
    image: ghcr.io/xbapps/xbvr:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./xbvr/config:/root/.config
      - /media/hdd2/vr:/videos
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
      - CLAIM=claim-cwik1_ETzP6Srcg7h-xH
      - TZ=Europe/Amsterdam
    volumes:
      - ./plex/config:/config
      - /media/hdd1/music:/music
  # adguardhome:
  #   container_name: adguardhome
  #   image: adguard/adguardhome
  #   ports:
  #     - 53:53/tcp
  #     - 53:53/udp
  #     - 80:80/tcp
  #     - 443:443/tcp
  #     - 443:443/udp
  #     - 3000:3000/tcp
  #   volumes:
  #     - ./adguardhome/work:/opt/adguardhome/work
  #     - ./adguardhome/conf:/opt/adguardhome/conf
  #   restart: unless-stopped
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
      - WEBPASSWORD=
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Amsterdam
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 4 * * 1
